[project]
name = "dev"
version = "0.0.1.dev1"
description = "Tools for developers."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "christianwhocodes", email = "dev@christianwhocodes.space" },
]
requires-python = ">=3.12"
dependencies = ["pyperclip>=1.11.0", "rich>=14.2.0"]

[project.scripts]
dev = "dev.cli:main"

[project.urls]
Homepage = "https://github.com/christianwhocodes/dev"
Repository = "https://github.com/christianwhocodes/dev"
Issues = "https://github.com/christianwhocodes/dev/issues"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"
